name: 'Daniel-MBSI-NLP-Demo'
channels:
  - conda-forge
dependencies:
  - python=3.9
  - spacy=3.0
  - numpy
  - pip
  - pip:
    - scispacy
    - https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.4.0/en_core_sci_sm-0.4.0.tar.gz